apiVersion: v1
kind: Service
metadata:
  name: nma-go-service
spec:
  type: ClusterIP
  selector:
    app: nma-go-app
  ports:
    - protocol: TCP
      port: 80         # Puerto por el que accederás al servicio
      targetPort: 8080 # Puerto que escucha tu app de Go
