apiVersion: v1
kind: Service
metadata:
  name: go-sample-service
spec:
  type: ClusterIP # Usa LoadBalancer si quieres una IP pública (si tu nube lo permite)
  selector:
    app: go-sample-app
  ports:
    - protocol: TCP
      port: 80      # Puerto externo
      targetPort: 8080 # Puerto interno de tu app Go
